language: python
install: "pip install tox"
script: "tox -e $TRAVIS_BUILD"
python: 3.5
env: TRAVIS_BUILD=py35

matrix:
  allow_failures:
    - env: TRAVIS_BUILD=deploy
  fast_finish: true
  include:
    - python: 3.5
      env: TRAVIS_BUILD=coverage
      before_install: "pip install codecov"
      after_success: "codecov"
    - python: 3.5
      dist: trusty
      sudo: false
      env: TRAVIS_BUILD=lint
      before_install: "nvm use stable"
      script: "make && make lint"
    - python: 3.5
      dist: trusty
      sudo: required
      before_install: "sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils"
      install: |
        . $HOME/.nvm/nvm.sh
        nvm install stable
        nvm use stable
        pip install pyinstaller
        pip install -e .
      script: "make -C gui dist"
      env: TRAVIS_BUILD=deploy
    - language: node
      node_js: node
      os: osx
      install: |
        brew update
        brew install python3
        pip3 install pyinstaller beancount
        pip3 install -e .
      script: "make -C gui dist"
      env: TRAVIS_BUILD=deploy

cache:
  directories:
    - $HOME/.cache
    - $HOME/Library/Caches
