name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-py:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        py: ["3.13", "3.10"]
        make_target: ["test-py", "test-py-old-deps"]
        include:
          - os: "macos-latest"
            make_target: "test-py"
            py: "3.13"
          - os: "windows-latest"
            make_target: "test-py"
            py: "3.13"
          - os: "ubuntu-latest"
            make_target: "test-py"
            py: "3.14"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
      - uses: astral-sh/setup-uv@v7
      - run: touch src/fava/static/app.js
      - run: make ${{ matrix.make_target }}
  test-js:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["lts/*"]
        include:
          - os: "ubuntu-latest"
            node: "current"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
      - run: cd frontend && npm test
  lint-js:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: astral-sh/setup-uv@v7
      - run: cd frontend && npm ci
      - run: uv run --no-dev --group pre-commit pre-commit run -a eslint
      - run: cd frontend; npx tsc
      - run: cd frontend; npx svelte-check
  lint-python:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v7
      - run: touch src/fava/static/app.js
      - run: make mypy
